FROM ruby:2.6-alpine3.9

LABEL maintainer="zengfanpu@gmail.com"

# Minimal requirements to run a Rails app
RUN apk add --no-cache --update build-base \
                                linux-headers \
                                git \
                                postgresql-dev \
                                nodejs \
                                tzdata \
                                mysql-client

ENV APP_PATH /usr/src/app

# Different layer for installation of gems
WORKDIR $APP_PATH
ADD Gemfile $APP_PATH
ADD Gemfile.lock $APP_PATH

RUN bundle install

# Copy application to container
COPY . APP_PATH
EXPOSE 3000

CMD ["rails", "serve"]
