FROM ruby:2.6-alpine3.9

LABEL maintainer="zengfanpu@gmail.com"

# Minimal requirements to run a Rails app
RUN apk add --no-cache --update build-base \
                                linux-headers \
                                git \
                                tzdata \
                                sqlite-dev \
                                nodejs

ENV APP_PATH /home/app/autolab

# Different layer for installation of gems
WORKDIR $APP_PATH
ADD Gemfile $APP_PATH
ADD Gemfile.lock $APP_PATH

RUN bundle install --without production

# Copy application to container
COPY . $APP_PATH
COPY ./config/school.yml.template $APP_PATH/config/school.yml
COPY ./config/database.docker-dev.yml $APP_PATH/config/database.yml
COPY ./config/initializers/devise.docker-dev.rb $APP_PATH/config/initializers/devise.rb
EXPOSE 3000

CMD ["rails", "server"]
